apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ .Values.kioskSimulator.service.name }}
  name: {{ .Values.kioskSimulator.service.name }}
spec:
  type: {{ .Values.kioskSimulator.service.type }}
  ports:
    - name: "http"
      port: {{ .Values.kioskSimulator.service.port }}
      targetPort: {{ .Values.kioskSimulator.service.targetPort }}
  selector:
    app: {{ .Values.kioskSimulator.service.name }}
